import {
  getRiskArea,
  isDocFile,
  isGeneratedFile,
  isLowValueFile,
  isTestFile,
  resolveRiskArea,
  riskAreaLabel,
  riskAreaPriority,
} from "./classifier.js";
import type { ConfigMatcher } from "./config.js";
import type { AnalysisExplanation, ChangedFile, RiskAreaId } from "./types.js";

const KIND_ORDER: Record<AnalysisExplanation["kind"], number> = {
  "risk-area": 0,
  generated: 1,
  "low-review-value": 2,
  test: 3,
  docs: 4,
  binary: 5,
  rename: 6,
  copy: 7,
};

function builtinRiskRuleId(area: RiskAreaId): string {
  return `builtin.path.${area}`;
}

function configRiskRuleId(area: RiskAreaId): string {
  return `config.paths.risk.${area}`;
}

interface ExplanationInput {
  path: string;
  kind: AnalysisExplanation["kind"];
  ruleId: string;
  source: AnalysisExplanation["source"];
  reason: string;
  area?: RiskAreaId;
  pattern?: string;
}

function makeExplanation(input: ExplanationInput): AnalysisExplanation {
  return {
    path: input.path,
    kind: input.kind,
    ruleId: input.ruleId,
    source: input.source,
    reason: input.reason,
    ...(input.area === undefined ? {} : { area: input.area }),
    ...(input.pattern === undefined ? {} : { pattern: input.pattern }),
  };
}

function explainRiskArea(
  classificationPaths: string[],
  matcher: ConfigMatcher,
): ExplanationInput | undefined {
  for (const path of classificationPaths) {
    const builtInArea = getRiskArea(path);
    const configMatch = matcher.matchRiskArea(path);
    const resolved = resolveRiskArea(builtInArea, configMatch?.area);
    if (resolved === undefined) continue;

    const chosenConfig =
      configMatch !== undefined &&
      resolved === configMatch.area &&
      (builtInArea === undefined || riskAreaPriority(configMatch.area) < riskAreaPriority(builtInArea));

    const hasConflict =
      builtInArea !== undefined && configMatch !== undefined && builtInArea !== configMatch.area;
    const loser = chosenConfig ? builtInArea : configMatch?.area;
    const conflictSuffix =
      hasConflict && loser !== undefined
        ? ` Primary area is ${resolved} because it ranks above ${loser} in the deterministic risk priority.`
        : "";

    if (chosenConfig && configMatch !== undefined) {
      return {
        path,
        kind: "risk-area",
        ruleId: configRiskRuleId(resolved),
        source: "config",
        reason: `Path matched the config ${resolved} risk pattern ${configMatch.pattern}.${conflictSuffix}`,
        area: resolved,
        pattern: configMatch.pattern,
      };
    }

    return {
      path,
      kind: "risk-area",
      ruleId: builtinRiskRuleId(resolved),
      source: "builtin",
      reason: `Path matched the built-in ${riskAreaLabel(resolved).toLowerCase()} rule.${conflictSuffix}`,
      area: resolved,
    };
  }

  return undefined;
}

function explainFile(file: ChangedFile, matcher: ConfigMatcher): AnalysisExplanation[] {
  const explanations: ExplanationInput[] = [];
  const classificationPaths = [
    file.path,
    ...(file.previousPath === undefined ? [] : [file.previousPath]),
  ];

  const riskExplanation = explainRiskArea(classificationPaths, matcher);
  if (riskExplanation !== undefined) explanations.push(riskExplanation);

  if (file.isGenerated) {
    const configPattern = matcher.matchGenerated(file.path);
    if (isGeneratedFile(file.path)) {
      explanations.push({
        path: file.path,
        kind: "generated",
        ruleId: "builtin.path.generated",
        source: "builtin",
        reason: "Path matched a built-in generated-file rule.",
      });
    } else if (configPattern !== undefined) {
      explanations.push({
        path: file.path,
        kind: "generated",
        ruleId: "config.paths.generated",
        source: "config",
        reason: `Path matched the config generated pattern ${configPattern}.`,
        pattern: configPattern,
      });
    } else {
      explanations.push({
        path: file.path,
        kind: "generated",
        ruleId: "builtin.git.generated",
        source: "git",
        reason: "Marked generated by the Git linguist-generated attribute.",
      });
    }
  }

  const lowValueConfigPattern = matcher.matchLowReviewValue(file.path);
  if (isLowValueFile(file.path)) {
    explanations.push({
      path: file.path,
      kind: "low-review-value",
      ruleId: "builtin.path.low-review-value",
      source: "builtin",
      reason: "Path matched a built-in low-review-value rule.",
    });
  } else if (lowValueConfigPattern !== undefined) {
    explanations.push({
      path: file.path,
      kind: "low-review-value",
      ruleId: "config.paths.lowReviewValue",
      source: "config",
      reason: `Path matched the config low-review-value pattern ${lowValueConfigPattern}.`,
      pattern: lowValueConfigPattern,
    });
  }

  const testConfigPattern = matcher.matchTest(file.path);
  if (isTestFile(file.path)) {
    explanations.push({
      path: file.path,
      kind: "test",
      ruleId: "builtin.path.test",
      source: "builtin",
      reason: "Path matched a built-in test rule.",
    });
  } else if (testConfigPattern !== undefined) {
    explanations.push({
      path: file.path,
      kind: "test",
      ruleId: "config.paths.tests",
      source: "config",
      reason: `Path matched the config test pattern ${testConfigPattern}.`,
      pattern: testConfigPattern,
    });
  }

  const docConfigPattern = matcher.matchDoc(file.path);
  if (isDocFile(file.path)) {
    explanations.push({
      path: file.path,
      kind: "docs",
      ruleId: "builtin.path.docs",
      source: "builtin",
      reason: "Path matched a built-in documentation rule.",
    });
  } else if (docConfigPattern !== undefined) {
    explanations.push({
      path: file.path,
      kind: "docs",
      ruleId: "config.paths.docs",
      source: "config",
      reason: `Path matched the config documentation pattern ${docConfigPattern}.`,
      pattern: docConfigPattern,
    });
  }

  if (file.isBinary) {
    explanations.push({
      path: file.path,
      kind: "binary",
      ruleId: "builtin.git.binary",
      source: "git",
      reason: "Detected as a binary file by Git.",
    });
  }

  if (file.status === "renamed" && file.previousPath !== undefined) {
    explanations.push({
      path: file.path,
      kind: "rename",
      ruleId: "builtin.git.rename",
      source: "git",
      reason: `File renamed from ${file.previousPath}.`,
    });
  }

  if (file.status === "copied" && file.previousPath !== undefined) {
    explanations.push({
      path: file.path,
      kind: "copy",
      ruleId: "builtin.git.copy",
      source: "git",
      reason: `File copied from ${file.previousPath}.`,
    });
  }

  return explanations.map(makeExplanation);
}

function compareExplanations(a: AnalysisExplanation, b: AnalysisExplanation): number {
  if (a.path !== b.path) return a.path < b.path ? -1 : 1;
  if (a.kind !== b.kind) return KIND_ORDER[a.kind] - KIND_ORDER[b.kind];
  if (a.ruleId !== b.ruleId) return a.ruleId < b.ruleId ? -1 : 1;
  if (a.source !== b.source) return a.source < b.source ? -1 : 1;
  return 0;
}

export function buildExplanations(
  files: ChangedFile[],
  matcher: ConfigMatcher,
): AnalysisExplanation[] {
  return files.flatMap((file) => explainFile(file, matcher)).sort(compareExplanations);
}
